### ISSUE TITLE
There is not "data" file on the folder results when running "1_PCA_RC.sh"

### ISSUE THREAD

**Issue by munozdjp** [pvlachas/LearningEffectiveDynamics#1]
Hello, I hope you're doing well. I was attempting to reproduce the results of your paper using the file `1_PCA_RC.sh`, but I encountered an error. It appears that the 'data' file is not being created and as a result, I am getting the following error message: 

`ValueError: [Error] Dimensionality reduction results /home/munozdjp/Documents/Methods/Results/FHN/Trained_Models/DimRed-scaler_MinMaxZeroOne-METHOD_pca-LD_6/data not found. 
`
Would you be able to provide any assistance or guidance on how I can resolve this issue? Thank you.

**Comment by pvlachas** [comment]
Hi, the script `1_PCA_RC.sh` trains the Reservoir computer on a latent space provided by PCA. In order to do that, you first need to "train" the PCA, in this case use the script `0_PCA.sh` first to fit the PCA and identify the latent space, and then use the script `1_PCA_RC.sh` to load the trained PCA weights and fit the RC.
Let me know if that answers your question!

**Comment by munozdjp** [comment]
It was solved, yes. Thanks
